language: node_js
node_js: node
sudo: false

before_script: npm prune
script:
  - npm run build
  - npm run test
  - npm run lint

after_success:
  - npm run semantic-release
  - npm prune --production
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker build -t "$DOCKER_REPO_SLUG:$TRAVIS_BRANCH" .;
    docker images;
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push $DOCKER_REPO_SLUG:$TRAVIS_BRANCH;
    fi
